### ISSUE TITLE
MyContent Dto 수정 및 SecurityConfig 수정

### ISSUE THREAD

**Issue by yjjjwww** [Team-FAB/FAB-BE#34]
@FeelingXD 

SecurityConfig에 
```
.antMatchers("/api/my/**").permitAll()
```
추가해야할 것 같습니다!

dto/mycontent에 FavoriteArticleDto, MyArticleDto 내용들을 ArticlePageDto와 비슷하게 구성해야할 것 같습니다! 프론트에서 같은 PostCard로 불러오고 있어서 해당 값들이 필요할 것 같아요!(price, gender, nickname, email, ...)

죄송하지만 제가 ArticlePageDto를 작성할 때 createdDate로 해서 프론트 분들이 createdDate 값으로 받아오고 있습니다.. FavoriteArticleDto, MyArticleDto 부분 createDate를 createdDate로 수정하시면 프론트 분들이 바로 값을 받을 수 있을 것 같습니다. 🙇🏻‍♂️

**Comment by FeelingXD** [comment]
> .antMatchers("/api/my/**").permitAll()
우선 이부분을 제외한 fix 분에대한 커밋입니다. endpoint my에대한부분은 로그인을 전제로해야하고 모두에게 열려있어야하지는 않아도 된다고 생각합니다.
