### ISSUE TITLE
마이페이지 프로필 MyContent 수정 요청

### ISSUE THREAD

**Issue by YouJin-Cho** [Team-FAB/FAB-BE#55]
* 마이페이지 프로필 수정해야할 부분
: GET  ➡️ 초기화면  '연령대' 부분
: PATCH 후 다시 GET ➡️ 'minAge', 'maxAge' null 값으로 출력, preferredAge도 null

![스크린샷 2023-06-16 오후 4 16 28](https://github.com/Team-FAB/FAB-BE/assets/122290134/44e86940-d839-47a6-8fb5-10fb3fca25d5)

**Comment by FeelingXD** [comment]
#68  와함께 개선되었습니다. @YouJin-Cho  항상 감사합니다. :)
