### ISSUE TITLE
카카오 소셜 로그인 email 

### ISSUE THREAD

**Issue by kwonseona** [Team-FAB/FAB-BE#62]
게시글 수정 삭제 기능이 email을 기반으로 작동하기 때문에 카카오 소셜 로그인 시 email을 프론트 측으로 함께 넘겨주시면 감사드리겠습니다. 🫡

**Comment by FeelingXD** [comment]
Oauth2 기능이 추가되었습니다. :) 수고하셧습니다. @kwonseona
